# Generated by Django 3.1.2 on 2021-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210322_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Title')),
                ('profile', models.CharField(max_length=120, verbose_name='Title')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone')),
                ('skill', models.IntegerField(max_length=100, verbose_name='Skill')),
                ('about', models.TextField(verbose_name='About')),
            ],
        ),
    ]
