# Generated by Django 3.1.2 on 2021-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210322_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
