# Generated by Django 3.1.2 on 2021-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210323_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.CharField(max_length=50, verbose_name='Icon'),
        ),
    ]
