# Generated by Django 3.1.2 on 2021-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210323_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_avatar',
            field=models.ImageField(default=1, upload_to='', verbose_name='Author avatar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.CharField(max_length=50, verbose_name='Icon options: 1)ion-monitor 2)ion-code-working 3)ion-camera 4)ion-android-phone-portrait'),
        ),
    ]
